site_name: Enigma Protocol

theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'pink'
  logo: 'images/enigmawhite.png'


  extra_css:
  - 'stylesheets/extra.css'

  markdown_extensions:
  - admonition

  extra:
    feature:
      tabs: true
    social:
      - type: 'github'
        link: 'https://github.com/enigmampc'
      - type: 'twitter'
        link: 'https://twitter.com/enigmampc'
      - type: 'linkedin'
        link: 'https://linkedin.com/in/#'


nav:
  - About Enigma: index.md
  - About Discovery: NewForDiscovery.md
  - Quick Start: Walkthrough.md
  - EnigmaJS:
    - About EnigmaJS: IntroductionToEnigmaJS.md
    - API: API.md
  - Secret Contracts:
    - Overview: SecretContracts.md
    - Supported Types: types.md
    - Examples: SecretContractExamples.md
  - Tutorials:
    - Learn Rust: RustWalkthrough.md
    - Deploy Discovery: NetworkSetup.md
    - Write a Secret Contract: Walkthrough_secretContract.md
  - FAQ: FAQ.md
  - Reference:
    - Enigma Components: IntroductionToReference.md
    - Enigma Technical Overview: EnigmaOverview.md
    - Secret Contract Engine: SecretContractEngine.md
    - Key Management: KeyManagement.md
  - Glossary: Glossary.md
  - License: License.md